#!/usr/bin/env bash
# install load balancer

sudo apt update -y
sudo apt install haproxy -y

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 6267-web-01 54.234.107.3:80 check
        server 6267-web-02 34.207.117.60:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
