#!/usr/bin/env bash
# redirection

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
configuration=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
        }
	location /redirect_me {
		return 301 /watch?v=QH2-TGUlwu4;
	}
}
"
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "$configuration" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
